---
- name: Install Nginx
  apt: name=nginx state=present
  register:
    nginxinstalled
  tags:
    - packages
    - nginx-revproxy

- name: Install certbot
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: /usr/bin/certbot-auto
    mode: "a+x"
  tags:
    - nginx-revproxy
    - lesencrypt